---
version: "2"
services:
  node:
    image: node:7.2.0-alpine
    container_name: pokerhand_node
    command: tail -f /dev/null
    volumes:
      - ./src:/home/node/src
      - ./node_modules:/home/node/node_modules
    working_dir: /home/node
