#!/usr/bin/env bash
set -ae -o pipefail

docker-compose up -d
docker exec -u node -t pokerhand_node npm install
docker exec -u node -t pokerhand_node npm run build

echo "♠♠♠♠♠♠♠♠♠♠♠♠♠♠♠♠♠♠♠♠♠♠♠♠♠"
echo "♠ Welcome To PokerHands ♠"
echo "♠♠♠♠♠♠♠♠♠♠♠♠♠♠♠♠♠♠♠♠♠♠♠♠♠"
echo "Press [CTRL+C] to stop.."
while true
do
    echo "Enter a hand"
    read hand1

    echo "Enter another hand"
    read hand2

    docker exec -u node -t pokerhand_node node build/app.js --hand1="$hand1" --hand2="$hand2"
done


